### ISSUE TITLE
Fix All Inline Methods

### ISSUE THREAD

**Issue by mikedegeofroy** [shampsdev/dishdash-miniapp#78]
Разделить объявление и реализацию функционала как вот например:

https://github.com/shampsdev/dishdash-miniapp/blob/fcb8deda3ff4b12327a58e586e5e0348d4ed55ae/src/modules/game/card.tsx#L79-L92

<sub><a href="https://huly.app/guest/shampsdev?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU3MjFkMTFlMDYzMmRkMDhlMjhhODUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctdGVhbS1zaGFtcHNkZXYtNjcwMTY1NjEtMWI2MmI5ZWUyNy1hOGVjMzkifQ.p6nPpya2Ome8mgqXsfrokqE7yugOCSfep2b5Arf8ghA">Huly&reg;: <b>DD-176</b></a></sub>

**Comment by PriestFaria** [comment]
> За одно надо кстати починить логику перехода между картинками в карточке

в плане? вроде все работает..
